#!/bin/bash
second statement
#!/bin/bash
Today I have learnt that ,Bash is a Unix shell and command language written by Brian Fox for the GNU Project as a free software replacement for the Bourne shell. Bash can also read and execute commands from a file, called a shell script. it supports filename globbing (wildcard matching), piping, here documents, command substitution, ariables, and control structures for condition testing and iteration.The keywords, syntax, dynamically scoped variables and other basic features of the language are all copied from sh.The shell's name is an acronym for Bourne Again Shell, a pun on the name of the Bourne shell that it replaces
